// <auto-generated />
using System;
using BeautyBookBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyBookBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeautyBookBackend.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MakeupArtistProfileMUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MakeupArtistProfileMUAId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.ChatRoom", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MakeupArtistProfileMUAId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatRoomId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MakeupArtistProfileMUAId");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.MUAStyle", b =>
                {
                    b.Property<Guid>("MUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StyleId")
                        .HasColumnType("int");

                    b.Property<Guid?>("MakeupArtistProfileMUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MakeupStyleStyleId")
                        .HasColumnType("int");

                    b.HasKey("MUAId", "StyleId");

                    b.HasIndex("MakeupArtistProfileMUAId");

                    b.HasIndex("MakeupStyleStyleId");

                    b.ToTable("MUAStyles");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.MakeupArtistProfile", b =>
                {
                    b.Property<Guid>("MUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("PortfolioCoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RatingAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("int");

                    b.HasKey("MUAId");

                    b.ToTable("MakeupArtistProfiles");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.MakeupStyle", b =>
                {
                    b.Property<int>("StyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StyleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StyleId");

                    b.ToTable("MakeupStyles");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Portfolio", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MakeupArtistProfileMUAId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PortfolioId");

                    b.HasIndex("MakeupArtistProfileMUAId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.ProductReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MakeupArtistProfileMUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MakeupArtistProfileMUAId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("MUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MakeupArtistProfileMUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceId");

                    b.HasIndex("MakeupArtistProfileMUAId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("MakeupArtistProfileMUAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("UserId");

                    b.HasIndex("MakeupArtistProfileMUAId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.WalletTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Booking", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyBookBackend.Models.MakeupArtistProfile", "MakeupArtistProfile")
                        .WithMany()
                        .HasForeignKey("MakeupArtistProfileMUAId");

                    b.HasOne("BeautyBookBackend.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MakeupArtistProfile");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.ChatRoom", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyBookBackend.Models.MakeupArtistProfile", "MakeupArtistProfile")
                        .WithMany()
                        .HasForeignKey("MakeupArtistProfileMUAId");

                    b.Navigation("Customer");

                    b.Navigation("MakeupArtistProfile");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.MUAStyle", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.MakeupArtistProfile", "MakeupArtistProfile")
                        .WithMany()
                        .HasForeignKey("MakeupArtistProfileMUAId");

                    b.HasOne("BeautyBookBackend.Models.MakeupStyle", "MakeupStyle")
                        .WithMany()
                        .HasForeignKey("MakeupStyleStyleId");

                    b.Navigation("MakeupArtistProfile");

                    b.Navigation("MakeupStyle");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.MakeupArtistProfile", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("BeautyBookBackend.Models.MakeupArtistProfile", "MUAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Message", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.ChatRoom", "ChatRoom")
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyBookBackend.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Portfolio", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.MakeupArtistProfile", "MakeupArtistProfile")
                        .WithMany()
                        .HasForeignKey("MakeupArtistProfileMUAId");

                    b.Navigation("MakeupArtistProfile");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.ProductReview", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyBookBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Review", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyBookBackend.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyBookBackend.Models.MakeupArtistProfile", "MakeupArtistProfile")
                        .WithMany()
                        .HasForeignKey("MakeupArtistProfileMUAId");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("MakeupArtistProfile");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Service", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.MakeupArtistProfile", "MakeupArtistProfile")
                        .WithMany()
                        .HasForeignKey("MakeupArtistProfileMUAId");

                    b.Navigation("MakeupArtistProfile");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.User", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.MakeupArtistProfile", "MakeupArtistProfile")
                        .WithMany()
                        .HasForeignKey("MakeupArtistProfileMUAId");

                    b.Navigation("MakeupArtistProfile");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.Wallet", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautyBookBackend.Models.WalletTransaction", b =>
                {
                    b.HasOne("BeautyBookBackend.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
