CREATE TABLE "MakeupStyles" (
    "StyleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100),
    "Description" character varying(255),
    CONSTRAINT "PK_MakeupStyles" PRIMARY KEY ("StyleId")
);


CREATE TABLE "Products" (
    "ProductId" uuid NOT NULL,
    "Name" character varying(255),
    "Brand" character varying(100),
    "Description" text,
    "ImageUrl" text,
    CONSTRAINT "PK_Products" PRIMARY KEY ("ProductId")
);


CREATE TABLE "Users" (
    "UserId" uuid NOT NULL,
    "FullName" character varying(100),
    "Email" character varying(255),
    "PasswordHash" text,
    "AvatarUrl" text,
    "PhoneNumber" character varying(20),
    "PhoneVerified" boolean NOT NULL,
    "Role" smallint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);


CREATE TABLE "MakeupArtistProfiles" (
    "MUAId" uuid NOT NULL,
    "Bio" text,
    "ExperienceYears" integer NOT NULL,
    "AverageRating" numeric(3,2) NOT NULL,
    "TotalBookings" integer NOT NULL,
    "PortfolioCoverUrl" text,
    "City" character varying(100),
    "Specialization" character varying(255),
    "SocialLinks" character varying(1000),
    "Status" smallint NOT NULL,
    "RankScore" integer NOT NULL,
    "ProfileQualityScore" integer NOT NULL,
    "ListedAt" timestamp with time zone,
    "LastActiveAt" timestamp with time zone,
    CONSTRAINT "PK_MakeupArtistProfiles" PRIMARY KEY ("MUAId"),
    CONSTRAINT "FK_MakeupArtistProfiles_Users_MUAId" FOREIGN KEY ("MUAId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);


CREATE TABLE "ProductReviews" (
    "ReviewId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProductReviews" PRIMARY KEY ("ReviewId"),
    CONSTRAINT "FK_ProductReviews_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductReviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE "Wallets" (
    "WalletId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Balance" numeric(18,2) NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Wallets" PRIMARY KEY ("WalletId"),
    CONSTRAINT "FK_Wallets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE "ChatRooms" (
    "ChatRoomId" uuid NOT NULL,
    "CustomerId" uuid NOT NULL,
    "MUAId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "MakeupArtistProfileMUAId" uuid,
    CONSTRAINT "PK_ChatRooms" PRIMARY KEY ("ChatRoomId"),
    CONSTRAINT "FK_ChatRooms_MakeupArtistProfiles_MakeupArtistProfileMUAId" FOREIGN KEY ("MakeupArtistProfileMUAId") REFERENCES "MakeupArtistProfiles" ("MUAId"),
    CONSTRAINT "FK_ChatRooms_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE "MUAStyles" (
    "MUAId" uuid NOT NULL,
    "StyleId" integer NOT NULL,
    "MakeupArtistProfileMUAId" uuid,
    "MakeupStyleStyleId" integer,
    CONSTRAINT "PK_MUAStyles" PRIMARY KEY ("MUAId", "StyleId"),
    CONSTRAINT "FK_MUAStyles_MakeupArtistProfiles_MakeupArtistProfileMUAId" FOREIGN KEY ("MakeupArtistProfileMUAId") REFERENCES "MakeupArtistProfiles" ("MUAId"),
    CONSTRAINT "FK_MUAStyles_MakeupStyles_MakeupStyleStyleId" FOREIGN KEY ("MakeupStyleStyleId") REFERENCES "MakeupStyles" ("StyleId")
);


CREATE TABLE "Portfolios" (
    "PortfolioId" uuid NOT NULL,
    "MUAId" uuid NOT NULL,
    "Title" text,
    "ImageUrl" text,
    "Description" character varying(500),
    "Tags" text[] NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "MakeupArtistProfileMUAId" uuid,
    CONSTRAINT "PK_Portfolios" PRIMARY KEY ("PortfolioId"),
    CONSTRAINT "FK_Portfolios_MakeupArtistProfiles_MakeupArtistProfileMUAId" FOREIGN KEY ("MakeupArtistProfileMUAId") REFERENCES "MakeupArtistProfiles" ("MUAId")
);


CREATE TABLE "Services" (
    "ServiceId" uuid NOT NULL,
    "MUAId" uuid NOT NULL,
    "ServiceName" character varying(100),
    "Description" character varying(500),
    "Price" numeric(18,2) NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "ImageUrl" text,
    "Tags" text[] NOT NULL,
    "MakeupArtistProfileMUAId" uuid,
    CONSTRAINT "PK_Services" PRIMARY KEY ("ServiceId"),
    CONSTRAINT "FK_Services_MakeupArtistProfiles_MakeupArtistProfileMUAId" FOREIGN KEY ("MakeupArtistProfileMUAId") REFERENCES "MakeupArtistProfiles" ("MUAId")
);


CREATE TABLE "WalletTransactions" (
    "TransactionId" uuid NOT NULL,
    "WalletId" uuid NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "TransactionType" smallint NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WalletTransactions" PRIMARY KEY ("TransactionId"),
    CONSTRAINT "FK_WalletTransactions_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("WalletId") ON DELETE CASCADE
);


CREATE TABLE "Messages" (
    "MessageId" uuid NOT NULL,
    "ChatRoomId" uuid NOT NULL,
    "SenderId" uuid NOT NULL,
    "Content" text,
    "SentAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_Messages_ChatRooms_ChatRoomId" FOREIGN KEY ("ChatRoomId") REFERENCES "ChatRooms" ("ChatRoomId") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE "PortfolioComments" (
    "Id" uuid NOT NULL,
    "PortfolioId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Content" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PortfolioComments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PortfolioComments_Portfolios_PortfolioId" FOREIGN KEY ("PortfolioId") REFERENCES "Portfolios" ("PortfolioId") ON DELETE CASCADE
);


CREATE TABLE "PortfolioLikes" (
    "Id" uuid NOT NULL,
    "PortfolioId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PortfolioLikes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PortfolioLikes_Portfolios_PortfolioId" FOREIGN KEY ("PortfolioId") REFERENCES "Portfolios" ("PortfolioId") ON DELETE CASCADE
);


CREATE TABLE "PortfolioSaves" (
    "Id" uuid NOT NULL,
    "PortfolioId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PortfolioSaves" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PortfolioSaves_Portfolios_PortfolioId" FOREIGN KEY ("PortfolioId") REFERENCES "Portfolios" ("PortfolioId") ON DELETE CASCADE
);


CREATE TABLE "Bookings" (
    "BookingId" uuid NOT NULL,
    "CustomerId" uuid NOT NULL,
    "MUAId" uuid NOT NULL,
    "ServiceId" uuid NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "Status" smallint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("BookingId"),
    CONSTRAINT "FK_Bookings_MakeupArtistProfiles_MUAId" FOREIGN KEY ("MUAId") REFERENCES "MakeupArtistProfiles" ("MUAId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Bookings_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("ServiceId") ON DELETE CASCADE,
    CONSTRAINT "FK_Bookings_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);


CREATE TABLE "Reviews" (
    "ReviewId" uuid NOT NULL,
    "BookingId" uuid NOT NULL,
    "CustomerId" uuid NOT NULL,
    "MUAId" uuid NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "MakeupArtistProfileMUAId" uuid,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId"),
    CONSTRAINT "FK_Reviews_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("BookingId") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_MakeupArtistProfiles_MakeupArtistProfileMUAId" FOREIGN KEY ("MakeupArtistProfileMUAId") REFERENCES "MakeupArtistProfiles" ("MUAId"),
    CONSTRAINT "FK_Reviews_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE INDEX "IX_Bookings_CustomerId" ON "Bookings" ("CustomerId");


CREATE INDEX "IX_Bookings_MUAId" ON "Bookings" ("MUAId");


CREATE INDEX "IX_Bookings_ServiceId" ON "Bookings" ("ServiceId");


CREATE INDEX "IX_ChatRooms_CustomerId" ON "ChatRooms" ("CustomerId");


CREATE INDEX "IX_ChatRooms_MakeupArtistProfileMUAId" ON "ChatRooms" ("MakeupArtistProfileMUAId");


CREATE INDEX "IX_Messages_ChatRoomId" ON "Messages" ("ChatRoomId");


CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");


CREATE INDEX "IX_MUAStyles_MakeupArtistProfileMUAId" ON "MUAStyles" ("MakeupArtistProfileMUAId");


CREATE INDEX "IX_MUAStyles_MakeupStyleStyleId" ON "MUAStyles" ("MakeupStyleStyleId");


CREATE INDEX "IX_PortfolioComments_PortfolioId" ON "PortfolioComments" ("PortfolioId");


CREATE INDEX "IX_PortfolioLikes_PortfolioId" ON "PortfolioLikes" ("PortfolioId");


CREATE INDEX "IX_Portfolios_MakeupArtistProfileMUAId" ON "Portfolios" ("MakeupArtistProfileMUAId");


CREATE INDEX "IX_PortfolioSaves_PortfolioId" ON "PortfolioSaves" ("PortfolioId");


CREATE INDEX "IX_ProductReviews_ProductId" ON "ProductReviews" ("ProductId");


CREATE INDEX "IX_ProductReviews_UserId" ON "ProductReviews" ("UserId");


CREATE INDEX "IX_Reviews_BookingId" ON "Reviews" ("BookingId");


CREATE INDEX "IX_Reviews_CustomerId" ON "Reviews" ("CustomerId");


CREATE INDEX "IX_Reviews_MakeupArtistProfileMUAId" ON "Reviews" ("MakeupArtistProfileMUAId");


CREATE INDEX "IX_Services_MakeupArtistProfileMUAId" ON "Services" ("MakeupArtistProfileMUAId");


CREATE INDEX "IX_Wallets_UserId" ON "Wallets" ("UserId");


CREATE INDEX "IX_WalletTransactions_WalletId" ON "WalletTransactions" ("WalletId");


